// <auto-generated />
using System;
using EventsPlus.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EventsPlus.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("EventsPlus.Models.AN", b =>
                {
                    b.Property<int>("PerformanceID")
                        .HasColumnType("int");

                    b.Property<int>("EquipmentID")
                        .HasColumnType("int");

                    b.Property<int>("AN_ID")
                        .HasColumnType("int");

                    b.Property<decimal?>("Actual_Costs")
                        .HasColumnType("Money");

                    b.Property<int?>("Amount_Needed")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("EquipmentsEquipmentTypeID")
                        .HasColumnType("int");

                    b.Property<decimal>("Estimated_Costs")
                        .HasColumnType("Money");

                    b.HasKey("PerformanceID", "EquipmentID");

                    b.HasIndex("EquipmentsEquipmentTypeID");

                    b.ToTable("AssetsNeeded");
                });

            modelBuilder.Entity("EventsPlus.Models.AT", b =>
                {
                    b.Property<int>("ActTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ActTypeID");

                    b.ToTable("ActType");
                });

            modelBuilder.Entity("EventsPlus.Models.Cust", b =>
                {
                    b.Property<int>("EventID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Age")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ContactNumber")
                        .HasMaxLength(11)
                        .HasColumnType("int");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<int>("EventsTypeOfEventID")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EventID");

                    b.HasIndex("EventsTypeOfEventID");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("EventsPlus.Models.Equip", b =>
                {
                    b.Property<int>("EquipmentTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Availability")
                        .HasColumnType("int");

                    b.Property<int>("EquipmentID")
                        .HasColumnType("int");

                    b.Property<int>("EquipmentTypeID1")
                        .HasColumnType("int");

                    b.Property<string>("Equipment_Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("EquipmentTypeID");

                    b.HasIndex("EquipmentTypeID1");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("EventsPlus.Models.EquipType", b =>
                {
                    b.Property<int>("EquipmentTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EquipmentTypeID");

                    b.ToTable("EquipmentType");
                });

            modelBuilder.Entity("EventsPlus.Models.Event", b =>
                {
                    b.Property<int>("TypeOfEventID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("End_Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventID")
                        .HasColumnType("int");

                    b.Property<string>("Event_Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Event_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Start_Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("TypeOfEventID1")
                        .HasColumnType("int");

                    b.HasKey("TypeOfEventID");

                    b.HasIndex("TypeOfEventID1");

                    b.ToTable("Event");
                });

            modelBuilder.Entity("EventsPlus.Models.EventLoc", b =>
                {
                    b.Property<int>("EventID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("EventLocationID")
                        .HasColumnType("int");

                    b.Property<int>("EventsTypeOfEventID")
                        .HasColumnType("int");

                    b.Property<string>("Location_Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("EventID");

                    b.HasIndex("EventsTypeOfEventID");

                    b.ToTable("EventLocation");
                });

            modelBuilder.Entity("EventsPlus.Models.OrgInfo", b =>
                {
                    b.Property<int>("OrganizerInfoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ContactNumber")
                        .HasMaxLength(11)
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("OrganizerInfoID");

                    b.ToTable("OrganizerInformation");
                });

            modelBuilder.Entity("EventsPlus.Models.OrgOcc", b =>
                {
                    b.Property<int>("OrganizerID")
                        .HasColumnType("int");

                    b.Property<int>("PerformanceID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrganizersOccupiedID")
                        .HasColumnType("int");

                    b.Property<int>("OrganizersOrganizerInfoID")
                        .HasColumnType("int");

                    b.Property<int>("OrganizersOrganizerRoleID")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("OrganizerID", "PerformanceID");

                    b.HasIndex("PerformanceID");

                    b.HasIndex("OrganizersOrganizerInfoID", "OrganizersOrganizerRoleID");

                    b.ToTable("OrganizersOccupied");
                });

            modelBuilder.Entity("EventsPlus.Models.OrgRole", b =>
                {
                    b.Property<int>("OrganizerRoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("OrganizerRoleID");

                    b.ToTable("OrganizerRole");
                });

            modelBuilder.Entity("EventsPlus.Models.Organizers", b =>
                {
                    b.Property<int>("OrganizerInfoID")
                        .HasColumnType("int");

                    b.Property<int>("OrganizerRoleID")
                        .HasColumnType("int");

                    b.Property<int>("OrganizerID")
                        .HasColumnType("int");

                    b.HasKey("OrganizerInfoID", "OrganizerRoleID");

                    b.HasIndex("OrganizerRoleID");

                    b.ToTable("Organizer");
                });

            modelBuilder.Entity("EventsPlus.Models.Participants", b =>
                {
                    b.Property<int>("PerformanceID")
                        .HasColumnType("int");

                    b.Property<int>("PerformerID")
                        .HasColumnType("int");

                    b.Property<decimal?>("Actual_Costs")
                        .HasColumnType("Money");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Estimated_Costs")
                        .HasColumnType("Money");

                    b.Property<int>("ParticipantID")
                        .HasColumnType("int");

                    b.Property<int>("PerformersActTypeID")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("PerformanceID", "PerformerID");

                    b.HasIndex("PerformersActTypeID");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("EventsPlus.Models.Performance", b =>
                {
                    b.Property<int>("EventID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventsTypeOfEventID")
                        .HasColumnType("int");

                    b.Property<int>("PerformanceID")
                        .HasColumnType("int");

                    b.Property<string>("Performance_Location")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Performance_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("EventID");

                    b.HasIndex("EventsTypeOfEventID");

                    b.ToTable("Performance");
                });

            modelBuilder.Entity("EventsPlus.Models.Performers", b =>
                {
                    b.Property<int>("ActTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("ActTypeID1")
                        .HasColumnType("int");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ContactNumber")
                        .HasMaxLength(11)
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PerformerID")
                        .HasColumnType("int");

                    b.HasKey("ActTypeID");

                    b.HasIndex("ActTypeID1");

                    b.ToTable("Performers");
                });

            modelBuilder.Entity("EventsPlus.Models.TOE", b =>
                {
                    b.Property<int>("TypeOfEventID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Event_Type")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("TypeOfEventID");

                    b.ToTable("TypeOfEvent");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("EventsPlus.Models.AN", b =>
                {
                    b.HasOne("EventsPlus.Models.Equip", "Equipments")
                        .WithMany("AssetsNeeded")
                        .HasForeignKey("EquipmentsEquipmentTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventsPlus.Models.Performance", "Performances")
                        .WithMany("AssetsNeeded")
                        .HasForeignKey("PerformanceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipments");

                    b.Navigation("Performances");
                });

            modelBuilder.Entity("EventsPlus.Models.Cust", b =>
                {
                    b.HasOne("EventsPlus.Models.Event", "Events")
                        .WithMany("Customers")
                        .HasForeignKey("EventsTypeOfEventID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Events");
                });

            modelBuilder.Entity("EventsPlus.Models.Equip", b =>
                {
                    b.HasOne("EventsPlus.Models.EquipType", "EquipmentType")
                        .WithMany("Equipment")
                        .HasForeignKey("EquipmentTypeID1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EquipmentType");
                });

            modelBuilder.Entity("EventsPlus.Models.Event", b =>
                {
                    b.HasOne("EventsPlus.Models.TOE", "TypeOfEvent")
                        .WithMany("Events")
                        .HasForeignKey("TypeOfEventID1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TypeOfEvent");
                });

            modelBuilder.Entity("EventsPlus.Models.EventLoc", b =>
                {
                    b.HasOne("EventsPlus.Models.Event", "Events")
                        .WithMany("EventLocations")
                        .HasForeignKey("EventsTypeOfEventID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Events");
                });

            modelBuilder.Entity("EventsPlus.Models.OrgOcc", b =>
                {
                    b.HasOne("EventsPlus.Models.Performance", "Performances")
                        .WithMany("OrganizersOccupieds")
                        .HasForeignKey("PerformanceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventsPlus.Models.Organizers", "Organizers")
                        .WithMany("OrganizersOccupieds")
                        .HasForeignKey("OrganizersOrganizerInfoID", "OrganizersOrganizerRoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organizers");

                    b.Navigation("Performances");
                });

            modelBuilder.Entity("EventsPlus.Models.Organizers", b =>
                {
                    b.HasOne("EventsPlus.Models.OrgInfo", "OrganizerInfo")
                        .WithMany("Organizers")
                        .HasForeignKey("OrganizerInfoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventsPlus.Models.OrgRole", "OrganizerRole")
                        .WithMany("Organizers")
                        .HasForeignKey("OrganizerRoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrganizerInfo");

                    b.Navigation("OrganizerRole");
                });

            modelBuilder.Entity("EventsPlus.Models.Participants", b =>
                {
                    b.HasOne("EventsPlus.Models.Performance", "Performances")
                        .WithMany("Participants")
                        .HasForeignKey("PerformanceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventsPlus.Models.Performers", "Performers")
                        .WithMany("Participants")
                        .HasForeignKey("PerformersActTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Performances");

                    b.Navigation("Performers");
                });

            modelBuilder.Entity("EventsPlus.Models.Performance", b =>
                {
                    b.HasOne("EventsPlus.Models.Event", "Events")
                        .WithMany("Performances")
                        .HasForeignKey("EventsTypeOfEventID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Events");
                });

            modelBuilder.Entity("EventsPlus.Models.Performers", b =>
                {
                    b.HasOne("EventsPlus.Models.AT", "ActType")
                        .WithMany("Performers")
                        .HasForeignKey("ActTypeID1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActType");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventsPlus.Models.AT", b =>
                {
                    b.Navigation("Performers");
                });

            modelBuilder.Entity("EventsPlus.Models.Equip", b =>
                {
                    b.Navigation("AssetsNeeded");
                });

            modelBuilder.Entity("EventsPlus.Models.EquipType", b =>
                {
                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("EventsPlus.Models.Event", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("EventLocations");

                    b.Navigation("Performances");
                });

            modelBuilder.Entity("EventsPlus.Models.OrgInfo", b =>
                {
                    b.Navigation("Organizers");
                });

            modelBuilder.Entity("EventsPlus.Models.OrgRole", b =>
                {
                    b.Navigation("Organizers");
                });

            modelBuilder.Entity("EventsPlus.Models.Organizers", b =>
                {
                    b.Navigation("OrganizersOccupieds");
                });

            modelBuilder.Entity("EventsPlus.Models.Performance", b =>
                {
                    b.Navigation("AssetsNeeded");

                    b.Navigation("OrganizersOccupieds");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("EventsPlus.Models.Performers", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("EventsPlus.Models.TOE", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
